// Generated by CoffeeScript 1.7.1
module.exports = function(grunt) {
  return grunt.registerMultiTask('browserify', 'Assembles JS files with browserify', function() {
    var CoffeeBrowserify, coffeeBrowserify, config, done, start;
    CoffeeBrowserify = require('./coffee_browserify');
    config = this.data;
    done = this.async();
    start = new Date();
    coffeeBrowserify = new CoffeeBrowserify();
    coffeeBrowserify.on('filename', function(filename) {
      return grunt.log.writeln("Included " + filename.cyan);
    });
    return coffeeBrowserify.run(config, (function(_this) {
      return function() {
        grunt.log.writeln("File " + config.dest.cyan + " created in " + ((new Date() - start) / 1000) + " seconds.");
        return done();
      };
    })(this));
  });
};
